# Generated by Django 3.1.6 on 2021-03-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdressDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30, verbose_name='Улица')),
                ('building', models.CharField(max_length=10, verbose_name='Дом/Строение')),
                ('letter', models.CharField(blank=True, max_length=20, null=True, verbose_name='Корпус/Литера')),
                ('room', models.CharField(blank=True, max_length=20, null=True, verbose_name='Помещение')),
            ],
            options={
                'ordering': ['street'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150, verbose_name='Наименование отдела/подзразделения')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сокращенное название')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.adressdepartment', verbose_name='Местонахождение')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('position', models.TextField(max_length=100, verbose_name='Должность')),
                ('phone_work', models.CharField(blank=True, max_length=15, null=True, verbose_name='Рабочий телефон')),
                ('phone_mob', models.CharField(blank=True, max_length=30, null=True, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office', models.CharField(blank=True, max_length=10, null=True, verbose_name='№ кабинета')),
                ('dob', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата рождения')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department', verbose_name='Отдел/подзразделение')),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
    ]
