# Generated by Django 3.1.6 on 2021-02-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(max_length=254, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('user_class', models.CharField(choices=[('Сторонний', 'Сторонний'), ('Сотрудник', 'Сотрудник'), ('Администратор', 'Администратор')], max_length=15, verbose_name='Категория пользователя')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.employee')),
            ],
        ),
    ]
