# Generated by Django 3.1.6 on 2021-03-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
