# Generated by Django 3.1.6 on 2021-02-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210213_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname']},
        ),
        migrations.AddField(
            model_name='department',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.TextField(max_length=100, verbose_name='Должность'),
        ),
    ]
